Крюков Александр м3237
CPP-KT/function_task pull request #12
Opened 2020-10-16 10:58 UTC by paskudnicc

2020-10-16 11:09 UTC, dzhiblavi requested changes

2020-10-16 11:09 UTC, dzhiblavi commented on function.h
> +    }
Копипаста

2020-10-16 11:09 UTC, dzhiblavi commented on function.h
> +        std::swap(obj, other.obj);
Здесь сработает `swap` над типом `aligned_storage`. Он не сделает `move` самих объектов, в случае если они хранятся в этом `aligned_storage` (то есть, они `small`). То есть, объект переметится в памяти, сам того не зная.

2020-10-16 11:09 UTC, dzhiblavi commented on function.h
> +                    to->obj = std::move(from->obj);
Такая же проблема, как и выше: происходит `move` типа `aligned_storage`, хотя перемещается реальный объект.

2020-10-16 13:34 UTC, dzhiblavi requested changes

2020-10-16 13:34 UTC, dzhiblavi commented on function.h
> +                    reinterpret_cast<T *&>(to->obj) = reinterpret_cast<T *&>(from->obj);
Может это и работает, но вряд ли вызывает `move`-конструктор, скорее просто конструктор копирования.

2020-10-16 13:34 UTC, dzhiblavi commented on function.h
> +            rhs.methods->move(this, &rhs);
Если есть `small`-объект, и у него бросающий `move`-конструктор, этот оператор не будет `noexcept`.

2020-10-16 13:34 UTC, dzhiblavi commented on function.h
> +    storage &operator=(const storage &rhs) {
А как же освободить текущий объект? (Сохранив при этом строгую гарантию исключений)

2020-10-16 15:58 UTC, dzhiblavi requested changes
1) Надо, чтобы вызывался именно `move`-конструктор, а не `operator=`.
2) Надо бысло исправить так, чтобы метод остался `noexcept`.
3) В конструкторе не нужно (нельзя) ничего удалять. Замечание относилось к `operator=`.

2020-10-30 18:30 UTC, paskudnicc commented
1. теперь вызывается move-конструктор в блоке try-catch
2. исправил
3. теперь это работает медленно и по-умному

2020-10-30 21:00 UTC, dzhiblavi requested changes

2020-10-30 21:00 UTC, dzhiblavi commented on function.h
> +                    }
Так прям совсем нельзя делать. Мы получается скрыли от пользователя информацию о том, что произошло исключение. Советую подумать, какое ограничение нужно ввести на тип, чтобы его считать маленьким и допустить до `move`-копирования

2020-11-01 07:51 UTC, dzhiblavi commented on function.h
> +                temp.methods->copy(this, &temp);
Эта штука сама по себе тоже может кинуть исключение. Да и какой смысл здесь именно копировать, если можно безопасно сделать `move`.

2020-11-01 07:51 UTC, closed without merging