Сластин Александр M3239
CPP-KT/function_task pull request #4
Opened 2020-10-11 13:24 UTC by aslastin

Не до конца разобрался, для чего в `T const* target() const noexcept` необходимо использовать в ветке `else` следующий кусок кода: `return reinterpret_cast<T* const&>(obj);`(180 строка кода), (исправил таким образом и тесты заработали). Изначально хотел сделать: `return reinterpret_cast<const T*&>(obj);`, что выглядит логично и совпадает с типом возврата функции (возвращаем указатель на константу), но компилятор требует константный указатель, причем непонятно для чего. Пожалуйста подскажите, почему необходимо указывать именно так. Заранее спасибо!

2020-10-13 16:59 UTC, dzhiblavi requested changes

2020-10-13 16:59 UTC, dzhiblavi commented on function.h
> +            [](obj_t obj, Args... args) -> R {
Почему бы не принимать во все подобные методы `obj_t*`? Тогда не надо будет создавать и копировать кучу `storage`-й.

2020-10-13 16:59 UTC, dzhiblavi commented on function.h
> +                reinterpret_cast<T*&>(fresh_obj) = new T(*reinterpret_cast<T*&>(obj));
Надо бы минимизировать количество `reinterpret_cast` по коду. С одной стороны, это копипаста, с другой -- каждый `reinterpret_cast` сам по себе опасная штука за которой надо следить. И чем их больше по коду, тем тяжелее.

2020-10-13 16:59 UTC, dzhiblavi commented on function.h
> +    function& operator=(function const& rhs) {
Сейчас здесь все хорошо. Но когда ты поменяешь в полях `methods` `obj_t` на `obj_t*` не забудь убедиться, что здесь все еще будет выполняться строгая гарантия исключений.

2020-10-30 08:37 UTC, aslastin commented on function.h
> +            [](obj_t obj, Args... args) -> R {
Возник вопрос касательно `aligned_storage`: чисто теоретически мы можем создать на месте `aligned_storage` некопируемый или немуваемый объект. А затем уже везде передавать `aligned_storage`, который является копируемым типом, тем самым нарушая свойства внутреннего объекта. Есть ли какой-то способ защититься от этого, да и вообще - плохо ли это?

2020-10-30 08:46 UTC, dzhiblavi commented on function.h
> +            [](obj_t obj, Args... args) -> R {
В этом и состоит ошибка, описанная выше. В понятие объекта входит в том числе его адрес в памяти, и его изменение без соответствующих методов нарушает всевозможные инварианты.

2020-10-30 10:17 UTC, aslastin commented on function.h
> +            [](obj_t obj, Args... args) -> R {
Исправил

2020-10-30 10:18 UTC, aslastin commented on function.h
> +                reinterpret_cast<T*&>(fresh_obj) = new T(*reinterpret_cast<T*&>(obj));
Я вынес `reinterpret_cast` в отдельные функции. Вы это хотели увидеть?

2020-10-30 16:21 UTC, dzhiblavi approved these changes

2020-10-30 16:25 UTC, dzhiblavi requested changes

2020-10-30 16:25 UTC, dzhiblavi commented on function.h
> +    }
Здесь ты делаешь `swap`, который перемещает байтики в `aligned_storage`, не глядя на структуру объектов (аналогичная ошибка была до этого)

2020-10-31 06:22 UTC, closed without merging