Done
CPP-KT/function_task pull request #7
Opened 2020-10-12 00:50 UTC by NelosG

2020-10-15 15:09 UTC, Tindarid commented on type_descriptor.h
> +        && (alignof(void *) % alignof(T) == 0 || alignof(void *) <= alignof(T));
Одна из проверок на `alignof` лишняя

2020-10-15 15:14 UTC, Tindarid commented on storage.h
> +    std::aligned_storage_t<sizeof(void *), alignof(void *)> buffer;
Слишком много раз продублирован `void*`

И переменная `small_storage` в отрыве от этого буффера (в другом файле)

2020-10-15 15:17 UTC, Tindarid commented on storage.h
> +            new(&(buffer)) T(std::move(val));
Не вижу нигде `delete`

Если тесты запустить под `valgring` то течёт память

2020-10-15 16:23 UTC, Tindarid commented on storage.h
> +            std::swap(buffer, temp.buffer);
Что-то мне не нравятся эти `swap`

Вдруг там внутри лежит объект, который not-trivially-copyable

2020-10-15 16:24 UTC, Tindarid commented on storage.h
> +    friend type_descriptor<RO, ArgsO...> const *empty_descriptor();
Эти `friend` функции выглядят, мягко говоря, странно

2020-10-15 16:25 UTC, Tindarid requested changes
Идейно верно, но есть баги

2020-10-15 22:28 UTC, NelosG commented on storage.h
> +            std::swap(buffer, temp.buffer);
Разве можно сделать оператор равно принимающий Lvalue  и ничего не копирующий?
Я скопировал объект в локальную переменную посвапал с зисом(тоже самое что  move, я переписал),
а дальше у лок переменной вызвался деструктор удалив те данные которые были в зисе до вызова оператора =;

2020-10-15 22:29 UTC, NelosG commented on storage.h
> +            new(&(buffer)) T(std::move(val));
fixed

2020-10-15 22:51 UTC, NelosG commented on storage.h
> +    std::aligned_storage_t<sizeof(void *), alignof(void *)> buffer;
fixed

2020-10-15 22:51 UTC, NelosG commented on type_descriptor.h
> +        && (alignof(void *) % alignof(T) == 0 || alignof(void *) <= alignof(T));
fixed

2020-10-15 23:04 UTC, NelosG commented on storage.h
> +    friend type_descriptor<RO, ArgsO...> const *empty_descriptor();
fixed

2020-10-15 23:10 UTC, NelosG commented on storage.h
> +    std::aligned_storage_t<sizeof(void *), alignof(void *)> buffer;
не совсем понимаю чем грозит то что она в другом файле, у меня же хэдера.

2020-10-15 23:18 UTC, NelosG commented on storage.h
> +            std::swap(buffer, temp.buffer);
а сам свап вроде как ничего не копирует

2020-10-17 21:22 UTC, Tindarid commented on storage.h
> +    std::aligned_storage_t<sizeof(void *), alignof(void *)> buffer;
Есть смысл держать весь ее функционал в одном файле, чтобы легче было его понимать и сопровождать

2020-10-17 21:28 UTC, Tindarid commented on storage.h
> +        && std::is_nothrow_move_constructible<T>::value
А где `include`?

2020-10-17 21:39 UTC, Tindarid commented on storage.h
> +            std::swap(buffer, temp.buffer);
Это все хорошо, конечно.

Свап - перемещает информацию, как минимум.

Например, у тебя есть объект, который как-то полагается на информацию где он лежит. Например, сохранил этот адрес (адрес своего поля etc.). А после этих операций он будет находится непонятно где и у него будет невалидный адрес, и никто ему об этом не скажет. Значит надо вызывать конструктор.

2020-10-17 21:47 UTC, Tindarid commented on storage.h
> +            std::swap(buffer, temp.buffer);
Впрочем, теперь нормально

2020-10-17 21:47 UTC, Tindarid commented
Принял, почитай комменты

2020-10-17 21:48 UTC, closed without merging

2020-10-17 22:12 UTC, NelosG commented on storage.h
> +        && std::is_nothrow_move_constructible<T>::value
include чего?

2020-10-17 22:14 UTC, Tindarid commented on storage.h
> +        && std::is_nothrow_move_constructible<T>::value
`std::is_nothrow_move_constructible` же не из воздуха берется?