Davydov Artyom M3238
CPP-KT/function_task pull request #8
Opened 2020-10-12 01:27 UTC by Dave11ar

2020-10-15 16:45 UTC, Tindarid commented on function.h
> +  fns::descriptor_base<R, Args...> *des;
`const *`?

2020-10-15 16:47 UTC, Tindarid commented on function.h
> +    swap(buf, other.buf);
А свапать `std::aligned_storage` - это хорошая идея?

2020-10-15 16:55 UTC, Tindarid commented on descriptor.h
> +descriptor_t<T, R, Args...> descriptor;
Глобальный объект в header файле?

2020-10-15 16:57 UTC, Tindarid commented on function.h
> +    swap(buf, other.buf);
Собственно, видимо поэтому `move` метод отсуствует у `descriptor`

2020-10-15 17:02 UTC, Tindarid requested changes
Fix it

2020-10-15 19:53 UTC, Dave11ar commented on descriptor.h
> +descriptor_t<T, R, Args...> descriptor;
Он же в неймспейсе fns

2020-10-15 20:16 UTC, Dave11ar commented on function.h
> +  fns::descriptor_base<R, Args...> *des;
fixed

2020-10-15 20:20 UTC, Dave11ar commented on function.h
> +    swap(buf, other.buf);
А почему `swap` `std::aligned_storage` плохая идея, у нас же вроде просто байты свопаются, а `size` и `align` у нас у всех одинаковый

2020-10-17 22:03 UTC, Tindarid commented on function.h
> +    rhs.des->move(&buf, &rhs.buf);
А что будет с объектом, который до этого был в этом `function`? Вроде, ты его перезатираешь

2020-10-17 22:32 UTC, Dave11ar commented on function.h
> +    rhs.des->move(&buf, &rhs.buf);
Справедливо, добавил `des->destroy(&buf)`

2020-10-17 22:52 UTC, Tindarid commented on descriptor.h
> +descriptor_t<T, R, Args...> descriptor;
Я, кстати так и не понял, почему не случается `redefinition`. Может расскажешь?)

Но тем не менее, люди извне, получают твой `descriptor`, и могут вызывать разные деструктивные операции

2020-10-18 00:55 UTC, Dave11ar commented on descriptor.h
> +descriptor_t<T, R, Args...> descriptor;
Действительно, не понимаю зачем положил его в `descriptor.h`, сделал приватной `static` переменной в `function.h`. Чтобы не было `redefinition` добавил `static'.

2020-10-18 20:44 UTC, closed without merging